version: "3.9"
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - sree
      - ceph.api
    extra_hosts:
      docker-root-host: "${DOCKER_GATEWAY_HOST:-192.168.1.4}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client_build:/usr/share/nginx/html
  sree:
    build: ./Sree
    restart: always
    container_name: sree
    ports:
      - "5555:5555"
  ceph.api:
    build: ./ceph.api
    restart: always
    container_name: ceph.api
    ports:
      - "81:81"
    environment:
      CEPH_ACCESS_KEY: QE378EYVP6S3XVIHZDC2
      CEPH_SECRET_KEY: UsmsGaQv6BINfFMAnZtlajR7Iq1IGdAXq6iMDBbI
      CEPH_SERVER: 192.168.1.4:8001
      CEPH_SERVER_EXTERNAL: 192.168.1.4:8001
      SREE_SERVER: 127.0.0.1:5555